apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
webhooks:
- clientConfig:
    caBundle: <you ca cert base64 here>
    service:
    url: /validate
  failurePolicy: Fail
  name: namespace-crud-limit.k8s.io
  namespaceSelector:
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - '*'
    resources:
    - namespaces